### ISSUE TITLE
Downloading shards

### ISSUE THREAD

**Issue by x4080** [Lightricks/LTX-Video#16]
In the inference, is the model downloading another model ?

there's Downloading shards 9.99GB

**Comment by v3ucn** [comment]
cuz need [PixArt](https://huggingface.co/PixArt-alpha/PixArt-XL-2-1024-MS)

**Comment by x4080** [comment]
I see, well can't run it in my GPU since it need at least 32GB, I'll close it for now

**Comment by loretoparisi** [comment]
> I see, well can't run it in my GPU since it need at least 32GB, I'll close it for now

It seems so

```
vae:/vae/vae_diffusion_pytorch_model.safetensors
unet:/unet/unet_diffusion_pytorch_model.safetensors
Downloading shards:   0%|                                                                                           | 0/2 [00:00<?, ?it/s]
model-00001-of-00002.safetensors:  43%|██████████████████████████▎                                   | 4.25G/9.99G [01:52<09:11, 10.4MB/s
```
But it seems it downloads all the time, not sure where, I cannot find it in the specified `ckpt_dir`.
