### ISSUE TITLE
vertical format?

### ISSUE THREAD

**Issue by MarisKay** [Lightricks/LTX-Video#49]
Hello, tried 704x1280 format, from image 2 image workflow, doesnt work at all. 1280x704 works, what is wrong?

**Comment by tylertheberator** [comment]
I've had **some** luck with referencing "portrait" and "landscape" in prompting.

**Comment by Shecht-ltx** [comment]
Hi @MarisKay 
Did you encounter an error or simply receive poor results?
Although the model wasn’t specifically trained on portrait aspect ratios, we’ve seen users on Discord share good results in that format.

**Comment by nitinmukesh** [comment]
@Shecht-ltx 

Please could you share the Discord channel

**Comment by MarisKay** [comment]
> Hi @MarisKay Did you encounter an error or simply receive poor results? Although the model wasn’t specifically trained on portrait aspect ratios, we’ve seen users on Discord share good results in that format.

Thank you so much for the replay, image provided for the img2video workflow appeared for fraction of second in a very beginning and then like a curtain of  dissolve effect.. everything turned into pale color with no further details and remained so for the rest of the video.

Knowing today's technologies, Insta, Ticktock etc.. they all require vertical videos, so leaving that out is like.. damn :/ Was not aware that it requires special training to run in different proportions. Looking forward.

**Comment by Shecht-ltx** [comment]
@nitinmukesh - https://discord.com/channels/1076117621407223829/1309520535012638740/1312518043091599381
